source :rubygems
gem "sinatra"
gem "json"
gem "uuidtools"

group :development do
  gem "pry"
  # Rerun versions greater than 0.6.2 cause keyboard characters to be repeated in the console
  # when you use ruby-debug or pry
  gem "rerun", "=0.6.2"
  gem "ruby-debug19"
end
